version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/mccurdyc/neighbor
    environment:
      - CODECOV_TOKEN="f99376f0-075d-4e6b-b622-c2750825193f"
      - GO111MODULE=on
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go build cmd/neighbor/main.go
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: go fmt ./...
      - run:
          when: on_success
          command: |
            bash <(curl -s https://codecov.io/bash)
